---
deployment:
  tasks:
    - export NODE_OPTIONS=--max_old_space_size=512
    - 'export DEPLOYPATH=${DEPLOYPATH:-public_html}'
    - 'echo "Starting deployment to: ${DEPLOYPATH}"'
    - 'test -n "${DEPLOYPATH}" || (echo "DEPLOYPATH is not set" && exit 1)'
    - 'echo "Deploy path resolved to: ${DEPLOYPATH}"'

    # Ensure target directories exist
    - '/bin/mkdir -p "${DEPLOYPATH}"'
    - '/bin/mkdir -p "${DEPLOYPATH}/api"'
    - '/bin/mkdir -p "${DEPLOYPATH}/includes"'

    # Remove legacy admin folder if present (we now deploy POS at root)
    - '/bin/rm -rf "${DEPLOYPATH}/admin" || true'

    # Deploy POS (root) - expects frontend built locally at frontend/dist
    - '/bin/rsync -av --delete frontend/dist/ "${DEPLOYPATH}/"'

    # Deploy root .htaccess for SPA routing
    - '/bin/rsync -av .htaccess "${DEPLOYPATH}/.htaccess"'

    # Deploy shared assets (logo)
    - '/bin/rsync -av frontend/public/logo-light.png "${DEPLOYPATH}/logo-light.png" || true'

    # Sync PHP API and includes
    - '/bin/rsync -av api/ "${DEPLOYPATH}/api/"'
    - '/bin/rsync -av includes/ "${DEPLOYPATH}/includes/"'

    # Show resulting tree for quick verification in the deploy log
    - '/bin/ls -la "${DEPLOYPATH}"'
    - '/bin/ls -la "${DEPLOYPATH}/api"'

    # Tighten permissions (optional)
    - '/bin/find "${DEPLOYPATH}" -type d -exec chmod 755 {} \;'
    - '/bin/find "${DEPLOYPATH}" -type f -exec chmod 644 {} \;'

    - 'echo "Deployment completed."'
