---
deployment:
  tasks:
    - export NODE_OPTIONS=--max_old_space_size=512
    - 'echo "Starting deployment to: ${DEPLOYPATH:-public_html/pos.theacumentechnologies.com}"'
    - 'test -n "${DEPLOYPATH:-public_html/pos.theacumentechnologies.com}" || (echo "DEPLOYPATH is not set" && exit 1)'

    # Ensure target directories exist
    - '/bin/mkdir -p "${DEPLOYPATH:-public_html/pos.theacumentechnologies.com}"'
    - '/bin/mkdir -p "${DEPLOYPATH:-public_html/pos.theacumentechnologies.com}/api"'
    - '/bin/mkdir -p "${DEPLOYPATH:-public_html/pos.theacumentechnologies.com}/includes"'

    # Sync React build files from root (already built locally)
    - '/bin/rsync -a --delete --exclude=".git" --exclude="node_modules" --exclude="frontend" --exclude="*.yml" --exclude="*.md" --exclude="*.sql" --exclude="*.js" --exclude="*.config.js" --exclude="package*" . "${DEPLOYPATH:-public_html/pos.theacumentechnologies.com}/"'

    # Sync PHP API and includes
    - '/bin/rsync -a api/ "${DEPLOYPATH:-public_html/pos.theacumentechnologies.com}/api/"'
    - '/bin/rsync -a includes/ "${DEPLOYPATH:-public_html/pos.theacumentechnologies.com}/includes/"'

    # Tighten permissions (optional, keep simple)
    - '/bin/find "${DEPLOYPATH:-public_html/pos.theacumentechnologies.com}" -type d -exec chmod 755 {} \;'
    - '/bin/find "${DEPLOYPATH:-public_html/pos.theacumentechnologies.com}" -type f -exec chmod 644 {} \;'

    - 'echo "Deployment completed."'
