---
deployment:
  tasks:
    - export NODE_OPTIONS=--max_old_space_size=512
    - 'export DEPLOYPATH=${DEPLOYPATH:-public_html}'
    - 'echo "Starting deployment to: ${DEPLOYPATH}"'
    - 'test -n "${DEPLOYPATH}" || (echo "DEPLOYPATH is not set" && exit 1)'

    # Ensure target directories exist
    - '/bin/mkdir -p "${DEPLOYPATH}"'
    - '/bin/mkdir -p "${DEPLOYPATH}/api"'
    - '/bin/mkdir -p "${DEPLOYPATH}/includes"'
    - '/bin/mkdir -p "${DEPLOYPATH}/admin"'

    # Deploy Shop (root) - expects shop built locally at shop/dist
    - '/bin/rsync -a --delete shop/dist/ "${DEPLOYPATH}/"'

    # Deploy POS (admin) - expects frontend built locally at frontend/dist
    - '/bin/rsync -a --delete frontend/dist/ "${DEPLOYPATH}/admin/"'

    # Deploy admin .htaccess for SPA routing
    - '/bin/rsync -a admin/.htaccess "${DEPLOYPATH}/admin/.htaccess"'

    # Deploy root .htaccess
    - '/bin/rsync -a .htaccess "${DEPLOYPATH}/.htaccess"'

    # Deploy shared assets (logo)
    - '/bin/rsync -a frontend/public/logo-light.png "${DEPLOYPATH}/logo-light.png"'

    # Sync PHP API and includes
    - '/bin/rsync -a api/ "${DEPLOYPATH}/api/"'
    - '/bin/rsync -a includes/ "${DEPLOYPATH}/includes/"'

    # Tighten permissions (optional)
    - '/bin/find "${DEPLOYPATH}" -type d -exec chmod 755 {} \;'
    - '/bin/find "${DEPLOYPATH}" -type f -exec chmod 644 {} \;'

    - 'echo "Deployment completed."'
